# Generated by Django 4.2.5 on 2023-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
